# Site settings
title: kssim
baseurl: ""
url: https://profile.kssim.com
enforce_ssl: profile.kssim.com
google_analytics: UA-116951375-1

# Author
author:
  name: KyeongSeob Sim
  desc: Software Programmer 
  email: ksub0912@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  github: kssim
  home: https://kssim.com
  blog: https://blog.kssim.com
  linkedin: https://www.linkedin.com/in/kssim/
  slideshare: https://www.slideshare.net/ssuser674248 
  wiki: https://wiki.kssim.com
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
